name: PKUAutoSubmit

on:
  schedule:
<<<<<<< HEAD
    - cron: '0 0,2 * * *'
=======
    - cron: '0 4 * * 3,4,5'
>>>>>>> 7c4d61cd3b899d1ead522b5b2c73906211f97127
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v2
        
      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
           python-version: 3.7
           
      - name: 'Install requirements'
<<<<<<< HEAD
        run: pip install selenium
        
      - name: 'Working'
        run: |
          sudo cp -p ./chromedriver/bin/chromedriver /usr/bin/
          chmod -R 777 /usr/bin/chromedriver
          chmod -R 777 ./chromedriver/bin/chromedriver
=======
        run: 
          pip install selenium
        
      - name: 'Working'
        run:
>>>>>>> 7c4d61cd3b899d1ead522b5b2c73906211f97127
          python main.py --ID ${{secrets.ID}} --PASSWORD ${{secrets.PASSWORD}} --MAIL_ADDRESS ${{secrets.MAIL_ADDRESS}} --PHONE_NUMBER ${{secrets.PHONE_NUMBER}} --SENDKEY ${{secrets.SENDKEY}}
          

